language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh
env:
  global:
  - PINS="io-page.dev:. io-page-unix.dev:. io-page-xen.dev:. io-page-js.dev:."
  - PACKAGE=io-page
  - DEPOPTS="io-page-unix io-page-xen io-page-js"
  matrix:
  - DISTRO="debian-stable" OCAML_VERSION=4.04
  - DISTRO="debian-stable" OCAML_VERSION=4.05
  - DISTRO="alpine"        OCAML_VERSION=4.06
  - DISTRO="alpine"        OCAML_VERSION=4.07
  - DISTRO="alpine"        OCAML_VERSION=4.08
